In [1]:
import pandas as pd

df = pd.read_csv("AI_Resume_Screening.csv")
df.head()

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [2]:
print(df.columns)

Index(['Resume_ID', 'Name', 'Skills', 'Experience (Years)', 'Education',
       'Certifications', 'Job Role', 'Recruiter Decision',
       'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)'],
      dtype='object')

In [4]:
import random
df['Gender'] = [random.choice(['Male', 'Female']) for _ in range(len(df))]
df['College Tier'] = [random.choice(['Tier-1', 'Tier-2', 'Tier-3']) for _ in range(len(df))]

In [5]:
df[['Name', 'Gender', 'College Tier']].head()

               Name  Gender College Tier
0        Ashley Ali  Female       Tier-3
1      Wesley Roman  Female       Tier-1
2     Corey Sanchez  Female       Tier-3
3  Elizabeth Carney  Female       Tier-1
4        Julie Hill    Male       Tier-2

In [6]:
df = df.drop(columns=['Name', 'Gender', 'College Tier'], errors='ignore')

df.head()

,Resume_ID,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [8]:
print(df.columns)

Index(['Resume_ID', 'Skills', 'Experience (Years)', 'Education',
       'Certifications', 'Job Role', 'Recruiter Decision',
       'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)'],
      dtype='object')

In [9]:
# Count number of skills
df['skill_count'] = df['Skills'].apply(lambda x: len(str(x).split(',')))

# Experience score
df['experience_score'] = df['Experience (Years)']

# Count certifications
df['cert_count'] = df['Certifications'].apply(lambda x: len(str(x).split(',')))

# Education score mapping
edu_map = {
    'b.tech': 3,
    'mba': 4,
    'phd': 5
}

def education_score(x):
    return edu_map.get(str(x).lower(), 1)

df['education_score'] = df['Education'].apply(education_score)

# Project score
df['project_score'] = df['Projects Count']

df.head()

,Resume_ID,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100),skill_count,experience_score,cert_count,education_score,project_score
0,1,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100,3,10,1,1,8
1,2,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100,4,10,1,4,1
2,3,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70,3,1,1,4,7
3,4,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95,3,7,1,3,0
4,5,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100,3,4,1,5,9

In [10]:
df['domain_match'] = df['Job Role']

In [11]:
df.to_csv("processed_resume_data.csv", index=False)